### ISSUE TITLE
CustomWindow support?

### ISSUE THREAD

**Issue by kdschlosser** [mrJean1/PyCocoa#2]
I am not seeing a class for CustomWindows. I am wanting to create a transparent window and I need the setOpaque method to do this.

Is this supported in this library??

**Comment by mrJean1** [comment]
To create a CustomWindow, subclass that from the `Window` class, like ...

```
from pycocoa import Window, YES
class CustomWindow(Window):
    ...
```

In general, you can get to the Obj-C properties and methods by using the `Window.NS` attribute, like

```
w = CustomWindow(title='Test')
o = w.NS.isOpaque()
...
```
However, using ...

```
w.NS.setOpaque(YES)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../PyCocoa/pycocoa/runtime.py", line 620, in __getattr__
    raise AttributeError('no %r [class]method or property: %s' % (name, self))
AttributeError: no 'setOpaque' [class]method or property: NSNull(<Id_t at 0x7f9ba565cf40>) of 0x7fff85b15000
```
doesn't work (at least not on macOS 10.15.6 Catalina).  Not sure why not, to be investigated further.

**Comment by mrJean1** [comment]
Correction.  Using ...
```
w.NS.setOpaque_(YES)  # or NO
```

does work for all 3 Python classes `Window`, `MediaWindow` and `TextWindow` (on macOS 10.15.6 Catalina).

**Comment by kdschlosser** [comment]
Thanks for checking into this for me. Glad to see it does work and that you will be adding convenience properties and methods to accommodate.

**Comment by mrJean1** [comment]
What about other things like `hasShadow`, `backgroundColor`, `titlebarAppearsTransparent` as mentioned [here](https://stackoverflow.com/questions/34531118/how-can-i-create-a-window-with-transparent-background-with-swift-on-osx)?

Instead of providing all those separately, would it be sufficient to add a new method `transparent` which sets all those to make the window transparent?

**Comment by mrJean1** [comment]
[PyCocoa20.11.8](https://pypi.org/project/PyCocoa/) is out and includes 3 new `Window` properties for to get/set the window to `opaque`, `transparent` and `transparentTitlebar`.  Please test and confirm or comment.

**Comment by mrJean1** [comment]
FYI, [PyCocoa 20.11.11](https://pypi.org/project/PyCocoa/) provides another `Window` property `alpha` to get/set the _AlphValue_ of the window, separate from `opaque` and `transparent`.

**Comment by kdschlosser** [comment]
I am sorry if I did not inform you that I do not have a way to test this. It is for a cross platform application that I am developing and at the present time I am unable to test any changes that you are making. I do have a MacBook but I am going to need to do a "hackintosh" OSX install in order to get a more recent version of OSX installed. Once I get some free time to do this I will. It is going to be a little while until I can get that done.
